name: isolate_rpc
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0-377.7.beta <3.0.0'


dependencies:
  event: ^2.0.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.12
